
## Dependencies:
mysqldemo:
  enabled: true


## Image Settings
image: plexinc/pms-docker
imageTag: latest
imagePullPolicy: Always
# imagePullSecrets: 
# - name: registry-secret

##Deployment Settings:
ReplicaCount: 1

## Environment variables
TZ: Europe/London



## Node selector
nodeSelector: {}

## Liveness & readiness probes
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

## Persist data to a persistent volume
persistence:
  enabled: true
  ## data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: azurefile
  accessMode: ReadWriteMany
  size: 50Gi
  annotations: {}

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 256Mi
    cpu: 100m



## Service
service:
  # type: LoadBalancer
  port: 80
  targetPort: 80


# To be added to the database server pod(s)
podAnnotations: {}

## Config for all dep charts
global:
  TZ: Europe/London
  PVC_CLAIMS:
    files: {{ template "plex.fullname" . }}
    downloads: plex-downloads
  deluge:
    image:
      repository: linuxserver/deluge
      tag: latest
  jackett:
    image:
      repository: linuxserver/jackett
      tag: latest
  nzbget:
    image:
      repository: linuxserver/nzbget
      tag: latest
  radarr:
    image:
      repository: linuxserver/radarr
      tag: latest
  sonarr:
    image:
      repository: linuxserver/sonarr
      tag: latest
  vpn:
    image:
      repository: dperson/openvpn-client
      tag: latest


configurationFiles:
  netherlands.ovpn: |-
    client
    dev tun
    proto udp
    remote nl.privateinternetaccess.com 1198
    resolv-retry infinite
    nobind
    persist-key
    # persist-tun # disable to completely reset vpn connection on failure
    cipher aes-128-cbc
    auth sha1
    tls-client
    remote-cert-tls server
    auth-user-pass /vpn/vpn.auth # to be reachable inside the container
    comp-lzo
    verb 1
    reneg-sec 0
    crl-verify /vpn/crl.rsa.2048.pem # to be reachable inside the container
    ca /vpn/ca.rsa.2048.crt # to be reachable inside the container
    disable-occ
    keepalive 10 30 # send a ping every 10 sec and reconnect after 30 sec of unsuccessfull pings
    pull-filter ignore "auth-token" # fix PIA reconnection auth error that may occur every 8 hours

  vpn.auth: |-

  crl.rsa.2048.pem: |-
  ca.rsa.2048.crt: |-