apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "vpn.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vpn.name" . }}
    helm.sh/chart: {{ include "vpn.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vpn.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vpn.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - args:
        - -r
        - 192.168.1.0/24
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.vpn.image.repository }}:{{ .Values.global.vpn.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8112
        securityContext:
          capabilities:
            add:
            - net_admin
        volumeMounts:
        - name: vpn-tun
          mountPath: /dev/net/tun
        - name: vpn-vpn
          mountPath: /vpn
      restartPolicy: Always
      volumes:
      - name: vpn-tun
        persistentVolumeClaim:
          claimName: {{ .Values.global.PVC_CLAIM.files }}
      - name: vpn-vpn
        persistentVolumeClaim:
          claimName: {{ .Values.global.PVC_CLAIM.files }}
      


