apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: vpn
  name: vpn
spec:
  ports:
  - name: "8112"
    port: 8112
    targetPort: 8112
  selector:
    io.kompose.service: vpn
status:
  loadBalancer: {}
