apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "plex.fullname" . }}
  labels:
    app: {{ template "plex.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.ReplicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "plex.fullname" . }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "plex.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: TZ
          value: {{ default "" .Values.TZ | quote }}
        ports:
        - containerPort: 32400
        - containerPort: 1900
        - containerPort: 3005
        - containerPort: 5353
        - containerPort: 8324
        - containerPort: 32410
        - containerPort: 32469
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "curl http://localhost"
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        volumeMounts:
        - name: plex-config
          mountPath: /config
        - name: plex-transcode
          mountPath: /transcode
        - name: plex-data
          mountPath: /data
        {{- if .Values.extraVolumeMounts }}
{{ tpl .Values.extraVolumeMounts . | indent 8 }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "plex.fullname" .) }}
      - name: plex-transcode
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "plex.fullname" .) }}
      - name: plex-data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "plex.fullname" .) }}



