
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "plex.fullname" . }}-azurefile
{{- with .Values.persistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "plex.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
{{- end }}

