
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "plex.fullname" . }}-app-secrets
  labels:
    app: {{ template "plex.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  DB_USERNAME: {{ .Values.DB_USERNAME | b64enc }}
  DB_PASSWORD: {{ .Values.DB_PASSWORD | b64enc }}
  DB_NAME: {{ .Values.DB_NAME | b64enc }}
  DB_HOST: {{ .Values.DB_HOST | b64enc }}
  REDIS_HOST": {{ .Values.REDIS_HOST | b64enc }}
  REDIS_PASSWORD: {{ .Values.REDIS_PASSWORD | b64enc }}
